### ISSUE TITLE
bind keyboard toggle to button

### ISSUE THREAD

**Issue by lav1422** [srm985/mok-project#27]
How can we able to bind the MOK key to particular id and how can we enable/disable mok keyboard

**Comment by srm985** [comment]
If I understand correctly, you would like to launch the keyboard by clicking a button - is this correct? Currently, the keyboard is displayed when a specified input-capable element (i.e. input, textarea, content editable div) is focused. This not only serves to trigger the keyboard but also helps it understand into which field it should input text. 

Could you help me better understand your idea to launch the keyboard with a button? Once you have clicked the button, how does the keyboard know into which field it should input text? Is there a specific button for each field? Is there only one field on the page? Is the field specifically scoped with the button? Understanding your goals will help me not only improve the keyboard for you, but potentially help others as well.

As far as enabling and disabling goes, the keyboard currently does not have this capability. I'm not sure why I never created this function but I have opened issue #28 to create enable/disable functionality and issue #29 to allow full destruction of the keyboard.
