### ISSUE TITLE
bind keyboard only on selected textboxes

### ISSUE THREAD

**Issue by madawadkar** [srm985/mok-project#37]
Is there a way we provide the popup keyboard only on selected text boxes instead of all textboxes in the page?

**Comment by srm985** [comment]
@madawadkar there currently is not a way to trigger the keyboard only for specific fields. I'm thinking this would be a valuable feature though. The first implementation idea that comes to my mind is adding a data attribute to the input fields you'd like ti have the keyboard. I'll work on this feature.

**Comment by srm985** [comment]
Implemented in Release V1.1.5.
